name: "CI"

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: elementary/docker:unstable
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          apt update
          apt install -y libgtk-3-dev valac meson libgranite-dev
      - name: Build
        # env:
        #   DESTDIR: out
        run: |
          meson build
          ninja -C build
          ninja -C build install
          xvfb-run -a -s "-screen 0 1024x768x24" \
            dbus-run-session meson test -C build --no-rebuild -v --no-stdsplit --wrap catchsegv
      - name: cleanup xvfb
        run: |
          xvfb_pids=`ps aux | grep tmp/xvfb-run | grep -v grep | awk '{print $2}'`
          if [ "$xvfb_pids" != "" ]; then
            echo "Killing the following xvfb processes: $xvfb_pids"
            sudo kill $xvfb_pids
          else
            echo "No xvfb processes to kill"
          fi
